Grupo 4 ejercicio 13/7
naipeloz/senpai-first-group-project pull request #5
Opened 2021-07-18 21:45 UTC by bcharletto

Mostrar el clima en Mvd, Caracas, Monterrey, El paso, Los Angeles.
Incluyendo temperatura, icono, humedad.
Implementar el darkmode

2021-07-18 22:10 UTC, naipeloz requested changes
Excelente trabajo!!!!! Les dejé algunos comentarios para que el código quede más organizado  y limpio. Eso no quita que estsuvo muy bien implementado, hagan los cambios y les va a quedar fantastico

2021-07-18 22:10 UTC, naipeloz commented on src/App.js
> +          isDarkMode={darkMode}
Identar

2021-07-18 22:10 UTC, naipeloz commented on src/api/caracas.js
> +const YOUR_ACCESS_KEY = 'bd4c948f6058e4f497cdc3d4a72b9e9a';
Esta muy bien implementado. Pero podrían dejar las dos funciones en un solo archivo

2021-07-18 22:10 UTC, naipeloz commented on src/api/elpaso.js
> +const YOUR_ACCESS_KEY = 'bd4c948f6058e4f497cdc3d4a72b9e9a';
Esta muy bien implementado. Pero podrían dejar las dos funciones en un solo archivo

2021-07-18 22:10 UTC, naipeloz commented on src/api/losangeles.js
> +
Esta muy bien implementado. Pero podrían dejar las dos funciones en un solo archivo

2021-07-18 22:10 UTC, naipeloz commented on src/api/monterrey.js
> +
Esta muy bien implementado. Pero podrían dejar las funciones en un solo archivo

2021-07-18 22:10 UTC, naipeloz commented on src/api/mvd.js
> +
Esta muy bien implementado. Pero podrían dejar las dos funciones en un solo archivo

2021-07-18 22:10 UTC, naipeloz commented on src/components/Weather/index.js
> +export default Weather;
Dejar una linea en blanco al final de todos los archivos

2021-07-18 22:10 UTC, naipeloz commented on src/pages/Weather.js
> +        console.log(response);
Cuando terminen de hacer los ejercicios no olviden eliminar los console logs

2021-07-18 22:10 UTC, naipeloz commented on src/pages/Weather.js
> +  const [climaMvd, setClimaMvd] = useState([]);
Podrian almacenar en una sola variable la informacion de todas las ciudades.
Algo como `const [climas, setClimas] = useState([{ciudad: 'Caracas',  data: {}}])`

2021-07-18 22:10 UTC, naipeloz commented on src/pages/Weather.js
> +     <div className={`${!props.isDarkMode ? 'bg-gray-200 text-black' : 'bg-gray-900 text-white'}`}>
Ya que es una validación que se repite en varios lados (la del darkMode) podrían hacerlo en una función aparte para que sea más organizado y reutlizable, algo más o menos así: 
`const handleDarkMode = () => !props.isDarkMode ? 'bg-gray-200 text-black' : 'bg-gray-900 text-white'`
.
.
.
`<div className={handleDarkMode()}>`

2021-07-18 22:10 UTC, naipeloz commented on src/pages/Weather.js
> +}
Espacio al final de los archivos

2021-07-19 23:33 UTC, bcharletto commented on src/api/mvd.js
> +
Te referis a las funciones getMontevideo, getMonterrey, getCaracas, etc...? ponerlas todas juntas en un solo archivo y exportarlas todas juntas?

2021-07-21 00:24 UTC, naipeloz approved these changes

2021-07-21 00:24 UTC, merged